"""Ordered preset queues for the CI supervisor (see supervisor.py).

A queue file is an ordered list of preset paths, resolved relative to
``ci/env/`` (this package's parent directory). Order is the scheduling
order: the supervisor hands jobs to runners starting at the front of the
list, one job at a time per runner (PRCI-style run queues; with a single
runner the queue order is exactly the run order).

Queue file format (the image each job runs is taken from the preset
itself; the queue only orders the jobs)::

    name: prci-gating
    jobs:
      - presets/prci/gating/simple_replication.yaml
      # a directory entry expands to all presets in it, sorted
      - presets/prci/nightly-latest/
      # per-job entry with metadata
      - preset: presets/azure/kerberos-flags.yaml
        note: Azure job "kerberos-flags"
"""

import os

import yaml

ENVROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


class QueueJob:
    def __init__(self, preset_rel, note=None):
        self.preset_rel = preset_rel  # relative to ENVROOT (ci/env)
        self.note = note
        self.path = os.path.join(ENVROOT, preset_rel)

    @property
    def key(self):
        """Filesystem-safe job key (remote workdir name)."""
        p = self.preset_rel
        if p.startswith('presets/'):
            p = p[len('presets/'):]
        p = p[:-len('.yaml')] if p.endswith('.yaml') else p
        return p.replace('/', '-')

    def __repr__(self):
        return f'QueueJob({self.preset_rel})'


class QueueSpec:
    def __init__(self, name, jobs, path=None):
        self.name = name
        self.jobs = jobs
        self.path = path

    @classmethod
    def from_file(cls, path):
        path = os.path.abspath(path)
        with open(path) as f:
            doc = yaml.safe_load(f) or {}
        name = doc.get('name') or os.path.splitext(
            os.path.basename(path))[0]
        jobs = []
        for entry in doc.get('jobs') or []:
            if isinstance(entry, dict):
                note = entry.get('note')
                preset = entry.get('preset') or entry.get('dir')
            else:
                note, preset = None, entry
            if preset is None:
                raise ValueError(f'{path}: job entry without preset/dir: '
                                f'{entry!r}')
            pdir = os.path.join(ENVROOT, preset)
            if isinstance(preset, str) and (preset.endswith('/')
                                            or os.path.isdir(pdir)):
                for fn in sorted(os.listdir(pdir)):
                    if fn.endswith('.yaml'):
                        jobs.append(QueueJob(preset.rstrip('/') + fn,
                                             note=note))
                continue
            jobs.append(QueueJob(preset, note=note))
        if not jobs:
            raise ValueError(f'{path}: empty queue (no jobs)')
        return cls(name, jobs, path)


def generate_prci_queue(defpath):
    """Render a queue YAML for a PRCI definition, in PRCI job order.

    Mappable jobs become preset references (the same paths
    ``migrate`` writes); skipped jobs become comments with the reason."""
    from . import prci

    defname = os.path.splitext(os.path.basename(defpath))[0]
    preset_dir = os.path.join('presets', 'prci', defname.replace('_', '-'))
    out = [
        f'# Ordered run queue for the PRCI definition `{defname}.yaml`',
        '# (job order = PRCI definition order; generated by',
        '# `freeipa-env queue generate`, like the presets it references).',
        'name: prci-' + defname.replace('_', '-'),
        'jobs:',
    ]
    for job_name, preset_name, reason, _built in prci.iter_jobs(defpath):
        if preset_name is None:
            out.append(f'  # {job_name}: skipped ({reason})')
        else:
            out.append(f'  - {preset_dir}/{preset_name}.yaml  # {job_name}')
    return '\n'.join(out) + '\n'
